POST http://jikaheimo.software:3000/api/posts HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphYWtvbnRlc3RhdXMiLCJpZCI6IjYwMzUzZTA5MDI2NDhjMjk2YTA1M2Y5YSIsImlhdCI6MTYxNDEwMjAyNX0.lfwaasVS6Z3Uzv4im-XC7Tyqlaf8wmSjDkBjUGAkq74

{
  "title": "Factory New Audi A4",
  "category": "cars",
  "description": "Very nice Audi A4",
  "deliveryType": {
    "pickup": true,
    "shipping": false
  },
  "askingPrice": 29.999
}


### UNAUTHORIZED

POST http://localhost:3000/api/posts HTTP/1.1
Content-Type: application/json

{
  "title": "Factory New Audi A4",
  "category": "cars",
  "description": "ads",
  "deliveryType": {
    "pickup": true,
  },
  "askingPrice": 3.99
}