POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "email": "testaaja123@test.com",
  "username": "Testaaja123",
  "address": {
    "city": "Oulu",
    "country": "Finland",
    "postalCode": 90550,
    "street": "Testaajantie 123"
  },
  "phoneNumber": "+358401231231",
  "birthDate": "1994-08-05",
  "password": "testaaja"
}