

### CREATE VALID USER
POST http://jikaheimo.software:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "email": "jaakontestaus123@testaaja.com",
  "username": "jaakontestaus",
  "address": {
    "city": "Kemi",
    "country": "Finland",
    "postalCode": "90550",
    "street": "Testaajantie 123"
  },
  "phoneNumber": "+123123123",
  "birthDate": "1994-08-05",
  "password": "jaakontestaus"
}

### CREATE USER WITH INVALID BODY
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "email": "testaaja33@test.com",
  "username": "Testaaja33",
  "address": {
    "city": "Oulu",
    "country": "Finland",
    "postalCode": 90550,
    "street": "Testaajantie 123"
  },
  "phoneNumber": "+358401231231",
  "birthDate": "1994-08-05",
  "password": "testaaja",
}